// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackerLib.Implementations;

namespace TrackerLib.Migrations
{
    [DbContext(typeof(UsageContext))]
    partial class UsageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TrackerLib.Models.AppUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceModelName");

                    b.Property<int>("Duration");

                    b.Property<string>("Package");

                    b.Property<string>("ParticipantIdentifier");

                    b.Property<DateTimeOffset>("TimeStamp");

                    b.Property<int>("UserCount");

                    b.HasKey("Id");

                    b.ToTable("AppUsages");
                });

            modelBuilder.Entity("TrackerLib.Models.DeviceUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceModelName");

                    b.Property<int>("EventType");

                    b.Property<string>("ParticipantIdentifier");

                    b.Property<DateTimeOffset>("TimeStamp");

                    b.Property<int>("UserCount");

                    b.HasKey("Id");

                    b.ToTable("DeviceUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
